### ISSUE TITLE
The icon is now missing

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.sigmyne.crush#1]
Probably something went wrong with the latest update https://flathub.org/apps/details/com.sigmyne.crush

**Comment by Nokia808** [comment]
Issue is still existing, & icon still crashed.

**Comment by attipaci** [comment]
I tried several things to fix. The appdata XML has a specification for a remote icon, which exists and loads in a browser without issues. It is what worked prior to the application update.

I did see that there is a newer specification on packaging icons with the application. I did have existing icons in the expected location in `share/icons/hicolor/<size>/app` but not with the standardized name. Hence, I created symlinks for `com.sigmyne.crush.png` to the existing icons. That did not work.

Looking at the source HTML of the application page on flathub, I noticed that it wants an icon for `com.sigmyne.show` instead. That's the icon for a launchable provided by the package, not the package itself. Why does the application page want an icon for a launchable, and not the application? Anyway, I did provide another symlink for the expected launchable icon name. Still did not work...

I was then wondering if flathub is perhaps not processing symlinks as expected for the icons (why not?). So, I replaced the symlinks with actual separate PNGs (waste of space, but hey). As far as I can tell it's still not working.

I'm running out of ideas. I have a valid external icon URL in the appdata XML. I have PNG icons packaged in the application itself (sizes 128x128, 64x64, 48x48, 32x32, and 16x16), at the specified locations in `/app/share/icons/hicolor/<size>/app`, with names both as `com.sigmyne.crush.png` and `com.sigmyne.show.png`. 

I welcome any insight into how I may be able to fix this...

Thanks,

**Comment by bilelmoussaoui** [comment]
Don't use t he symlinks. Just use the rename-icon to rename the icon later after the build finish on your flatpak manifest. You don't need to specify the icon in the metainfo at all. The icon belongs to the desktop file

**Comment by attipaci** [comment]
Thanks Bilal,

That's useful info and makes sense. Maybe someone could update [Requirements and Conventions](http://docs.flatpak.org/en/latest/conventions.html) page on flathub. Instead of describing how icons should be named, it should say to use `rename-icon` instead with just the file name (no path). An example may be useful also...

**Comment by attipaci** [comment]
I've updated the Flatpak build to use `rename-icon`, and published it. The flathub page still shows the broken icon, but maybe that's just a matter of time before it's updated?

**Comment by attipaci** [comment]
Well, renaming the icon works, but now it has another problem:

```
...
Renaming icon hicolor/128x128/apps/crush.png to hicolor/128x128/apps/com.sigmyne.crush.png
Renaming icon hicolor/48x48/apps/crush.png to hicolor/48x48/apps/com.sigmyne.crush.png
Renaming icon hicolor/32x32/apps/crush.png to hicolor/32x32/apps/com.sigmyne.crush.png
Renaming icon hicolor/16x16/apps/crush.png to hicolor/16x16/apps/com.sigmyne.crush.png
Renaming icon hicolor/64x64/apps/crush.png to hicolor/64x64/apps/com.sigmyne.crush.png
Rewriting contents of com.sigmyne.crush.desktop
Error: Can't load desktop file /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-k5qX40/files/share/applications/com.sigmyne.crush.desktop: Error opening file /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-k5qX40/files/share/applications/com.sigmyne.crush.desktop: No such file or directory
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-k5qX40
```

CRUSH is primarily a command-line tool, hence it does not (and should not) have a .desktop file. Why does the build insist on having one? (Just because I added a rename-icon for the package?)

The package does however contain one graphical tool named 'show', which is defined as a launchable in the manifest...

I think I'll need more help before I can continue...

**Comment by attipaci** [comment]
Update, I guess I can change "command" from "crush" to "show"... I'll try that...

**Comment by attipaci** [comment]
Nope. It still wants a `crush.desktop` after the `rename-icon` was added...

**Comment by attipaci** [comment]
To work around, I opted to avoid using rename-icon for now, and instead packaged my icons with the expected name `com.sigmyne.show.png` (the name the broken flathub link refers to). However, the icon files still do not propagate to the flathub page, it seems. The saga for a flathub icon continues...

**Comment by bilelmoussaoui** [comment]
Still, the installed icons are just symlinks to files that won't be exported because they don't start with the prefix which is your app-id.

**Comment by attipaci** [comment]
Bilal, if that's the case then flathub isn't using the latest manifest and tarball. There are no more symlinks in my icons folders (unless flatpak creates them as such during build)... If you want to check, look at the tarball referenced in the sources section of the manifest. The icons are under `crush/Install/posix/share/` after exploding the tarball...

**Comment by bilelmoussaoui** [comment]
Sorry I forgot about this, but if it's a CLI application, why the metainfo mentions it as a desktop application? https://github.com/attipaci/crush/blob/master/crush/Install/posix/share/metainfo/com.sigmyne.crush.appdata.xml#L3
The validations are different depending on whether it's a desktop/cli application. The cli applications are by the way not exposed on Flathub frontend yet.

**Comment by attipaci** [comment]
Well, crush is application bundle, with several CLI tools and one desktop component (the 'show' tool). So, counting is as a desktop application is not entirely misguided...

**Comment by attipaci** [comment]
Bilel, do you think if I packaged the same icons both as `com.sigmyne.show.png` (for the desktop component 'show') and as `com.sigmyne.crush.png` (after the name of the package), flathub will finally find the correct icon for the package?

**Comment by bilelmoussaoui** [comment]
You can't export files (icons, desktop, metainfo, dbus services) or anything that doesn't follow `$appid` or `$appid.*`. As your app-id is `com.sigmyne.crush`, in order to export the gui application, it has to use `com.sigmyne.crush.show` as app-id.

**Comment by attipaci** [comment]
OK, and that's what it used to be. But the flathub page is referencing `com.sigmyne.show.png`, which is why it does not work. I.e., the site is generated to look for the icon of the launchable, rather than appid...

**Comment by attipaci** [comment]
If I understand you correctly everything in the package must have `com.sigmyne.crush` prepended to it to be exported. So, if I change the following:

- Rename desktop file from `com.sigmyne.show.desktop` to `com.sigmyne.crush.show.desktop`.
- In above .desktop file, I can reference the package icon as `com.sigmyne.crush` (to use `icons/hicolor/<size>/apps/com.sigmyne.crush.png`).

And it should work, right?

I'm nearly ready to release a new version. I'll see if I can finally get this right...

**Comment by attipaci** [comment]
Hi Bilal. It looks like the icon is now OK with the latest release (and flatpak update). Thanks for all the help figuring out what was going on...
