### ISSUE TITLE
Fix launchable entry

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.sigmyne.crush#5]
```
<launchable type="desktop-id">com.sigmyne.crush.:show.desktop</launchable>
```

Is wrong and has some weird characters it should be `$FLATPAK_ID.desktop` exactly. You might need to rename the desktop file to fix this.

**Comment by attipaci** [comment]
Hi @bbhtt,

I'm trying to understand what's going on there. This seems to be a change in the builder. The json file has the following entry to rename the desktop file (`crush-show.desktop` originally) to what is expected by flatpak, i.e.:

```json
	"rename-desktop-file": "crush-show.desktop",
```
According to the documentation:
 
> __rename-desktop-file (string)__
>
> Any desktop file with this name will be renamed to a name based on id during the cleanup phase. The appdata file 
> launchable will be updated if needed.

But, apparently, the builder is failing to do the part about the launchable being updated also, resulting in that Frankenlauncher you mentioned above. I believe, this is a bug in the builder... 

Let me know if you disagree.

**Comment by bbhtt** [comment]
No the bug is that you already have a launchable in appdata which is bugged, so it is not updating it https://github.com/attipaci/crush/blob/3d798ef542f541efb17ef8e8b026811edda2cc50/crush/Install/posix/share/metainfo/crush.appdata.xml#L39

> rename the desktop file (crush-show.desktop originally)

The desktop file is installed as `show.desktop` without the `rename-desktop-file`.

It should work if you change the launchable to `show.desktop` then use the rename here.

```patch
--- a/Install/posix/share/metainfo/crush.appdata.xml	2024-04-23 12:59:20.463493029 +0530
+++ b/Install/posix/share/metainfo/crush.appdata.xml	2024-04-23 12:59:35.103786139 +0530
@@ -36,7 +36,7 @@
 <url type="bugtracker">https://github.com/attipaci/crush/issues</url>
 <url type="donation">https://paypal.me/attipaci</url>
 
-<launchable type="desktop-id">com.sigmyne.crush.:show.desktop</launchable>
+<launchable type="desktop-id">show.desktop</launchable>
 
 <releases>
 	<release version="2.50-3" type="stable" date="2020-01-03" urgency="medium">
```

**Comment by bbhtt** [comment]
Additionally you need to fix the following to pass appstream validation:

- https://github.com/attipaci/crush/blob/3d798ef542f541efb17ef8e8b026811edda2cc50/crush/Install/posix/share/metainfo/crush.appdata.xml#L133 should not be empty see https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#translations
- https://github.com/attipaci/crush/blob/3d798ef542f541efb17ef8e8b026811edda2cc50/crush/Install/posix/share/metainfo/crush.appdata.xml#L121-L123 should be removed it is automatically pulled from the desktop file which has the mimetype key

**Comment by bbhtt** [comment]
Fixing the launchable will also fix https://github.com/flathub/com.sigmyne.crush/issues/1, your flathub.org page is missing the app icon because of that.

**Comment by attipaci** [comment]
Thanks @bbhtt,

I see the problem now. It's been fixed in the upstream development branch since (hence I did not see it before), but it is messed up in the release tarball used as the upstream source. I'll patch it as you suggested. I also removed the `<translation />` tag (there is no translation available), and the mimetype.

**Comment by attipaci** [comment]
@bbhtt,

Thanks for the help on getting this straightened out. :-)
